# Numerical Python(Numpy) - Part1
    - test

In [5]:
# de facto standard (사실상의 표준)
import numpy as np

In [6]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
list(map(lambda x: 3 * x, a))

[3, 6, 9]

In [8]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

# 1. Numpy dimension

In [14]:
a = np.array([1,4,5,8], float)
print(a)

[1. 4. 5. 8.]


In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [18]:
a.dtype, a.shape

(dtype('float64'), (4,))

# 2. Array shape

In [19]:
# Vector(1차원 배열)
vec = np.array([1, 4, 5, 8])
vec.shape

(4,)

In [28]:
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [29]:
# Tensor (3차원 이상)

#tensor = np.array([[[],[]],[[],[]],[[],[]]])
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [30]:
tensor.shape

(2, 3, 4)

In [31]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [32]:
# size 는 element 의 개수
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [34]:
#a = np.array([1,2,3], dtype = np.float32)
a = np.array([1,2,3], np.float32)
a
#print(a)

array([1., 2., 3.], dtype=float32)

In [35]:
# int32가 default 이다
b = np.array([1,2,3], dtype = np.int16)
b

array([1, 2, 3], dtype=int16)

In [47]:
# reshape
matrix.shape

(2, 3)

In [48]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [49]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
# -1은 넘파이가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [51]:
matrix.reshape(3,-1).shape

(3, 2)

In [52]:
tensor.reshape(4,-1).shape

(4, 6)

In [53]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [54]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [55]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# flatten - 1차원으로 펼쳐줌

In [56]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [57]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 3. Indexing & Slicing

In [59]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
matrix.shape

(2, 3)

In [61]:
matrix[0][1]

2

In [63]:
matrix[0,1]

2

In [65]:
tensor[1,1,2]

19

## slicing

In [70]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [78]:
# 5,6,7 9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [81]:
#1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [91]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
X, y = b[:, :-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))

In [92]:
X, y

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([ 3,  7, 11, 15]))