In [4]:
import numpy as np

##### 저장
array = np.arange(0,10)
#print(array)
np.save("saved.npy",array)

#### 불러오기
result = np.load("saved.npy")
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2,2)
print(array)

result_array = array * 10
print(result_array)

[[6 3]
 [4 4]]


[[60 30]
 [40 40]]
