In [4]:
import numpy as np

In [5]:
list_data = [1,2,3]
list_data

[1, 2, 3]

In [6]:
array = np.array(list_data)
print(array)

[1 2 3]


In [11]:
print(array.size)
print(array.dtype)
print(array[2])

3
int32
3


In [12]:
# 0~3배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [13]:
array2 = np.zeros((4,4),dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
array3 = np.ones((4,4),dtype=str)
print(array3)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [16]:
# 0~9 까지 랜덤하게
array4 = np.random.randint(0,10,(3,3))
print(array4)

[[3 5 0]
 [4 7 5]
 [6 4 6]]


In [17]:
# 통계적 분포 배열 생성
# 평균이 0, 표준편차 1인 표준 정규분포 배열 생성
array5 = np.random.normal(0,1, (3,3))
print(array5)

[[ 0.46513864  0.9872131   0.47417364]
 [-1.37042929  0.15506573  1.12740738]
 [ 0.46785566 -0.05560374  2.15472342]]


In [19]:
# 배열 합치기
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [20]:
# 가로축 합치기
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2)

[[1 2]
 [3 4]]


In [26]:
#세로축 합치기
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)
array3 = np.concatenate([array1, array2],axis=0)
print(array3)


[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [31]:
array = np.arange(8).reshape(2,4)
print(array)
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(right.shape)
print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
